import {Dimensions, StyleSheet} from 'react-native';

let w = Dimensions.get('screen').width;
let h = Dimensions.get('screen').height;

export default StyleSheet.create({
  bg: {
    width: w,
    height: h,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  currency_container: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    width: w / 1.05,
    height: h / 6.5,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  currency_container_parent: {
    borderWidth: 0.8,
    borderColor: 'white',
    borderRadius: 20,
  },
  buySellHeader: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: w / 2.5,
    marginLeft: w / 2.9,
  },
  buySellText: {
    color: '#D1D1D1',
    fontFamily: 'OpenSans-Bold',
    fontSize: w / 14,
    elevation: 5,
    shadowColor: 'black',
    shadowOpacity: 0.1,
    paddingBottom: 5,
  },
  exchange_container_parent: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    width: w / 1.05,
    height: h / 3.3,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exchange_container: {
    borderWidth: 0.8,
    borderColor: 'white',
    borderRadius: 20,
    marginTop: 10,
  },
  exchange_textInput: {
    borderBottomWidth: 1.5,
    borderBottomColor: '#cccccc',
    width: w / 2.2,
    fontSize: 17,
  },
  exchange_currency_container: {
    flexDirection: 'row',
    width: w / 1.15,
    backgroundColor: '#ECECEC',
    borderRadius: 20,
    paddingLeft: 20,
    alignItems: 'center',
  },
  currencyType: {
    color: '#474747',
    fontFamily: 'OpenSans-Bold',
    fontSize: w / 15,
    paddingVertical: 13,
  },
  exchange_ımage: {
    width: 80,
    height: 80,
    margin: 10,
  },
  currencyType_container: {
    backgroundColor: 'white',
    flex: 1,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 30,
  },
  pen: {
    width: 23,
    height: 23,
    marginRight: -20,
  },
  card_container: {
    flexDirection: 'row',
    backgroundColor: '#ECECEC',
    width: w / 1.1,
    height: h / 16,
    alignItems: 'center',
    borderRadius: w / 20,
    marginBottom: 10,
  },
  card_currencyName_contianer: {
    backgroundColor: 'white',
    height: h / 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: w / 20,
    borderTopLeftRadius: w / 20,
    flexDirection: 'row',
    width: w / 3,
  },
  card_currencyName_Text: {
    color: '#474747',
    fontSize: w / 15,
    fontFamily: 'OpenSans-Bold',
    padding: 10,
  },
  card_currencyData_container: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flex: 10,
  },
  card_currencyData_text: {
    fontSize: w / 21,
    color: '#4f4f4f',
    fontFamily: 'OpenSans-Medium',
  },
  card_rightArrow_icon: {
    width: w / 15,
    height: h / 25,
  },
  card_rightArrow_container: {
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    height: h / 16,
    width: w / 8,
    borderTopRightRadius: w / 20,
    borderBottomRightRadius: w / 20,
  },
  card_greenArrow_icon: {
    width: 11,
    height: 16,
  },
  card_upDownArrow_container: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 8,
  },
  card_upDown_text: {
    color: 'green',
    fontSize: 11,
    fontFamily: 'OpenSans-Bold',
  },
});
